server:
  port: 8282
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth"
    username: "postgres"
    password: '{cipher}7f09ade83c4f0edafe62e423791ce0f0eba215b16e07883f40dfda90c120b2dd'
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
        format_sql: "true"
