server:
  port: 8282
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth"
    username: "postgres"
    password: "steaua"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: "true"
    properties:
      hibernate:
        format_sql: "true"
